[generate.cna]
allow = [
    # "adobe",
    "apache",
    "appcheck",
    "atlassian",
    #"canonical",
    "chrome",
    "cloudflare",
    "concretecms",
    "cpansec",
    "curl",
    "docker",
    "document fdn.",
    "eclipse",
    "eef",
    "elastic",
    "f5",
    "facebook",
    #"fedora",
    "gandc",
    "github_m",
    "github_p",
    "gitlab",
    "glibc",
    "go",
    "google",
    "govtech csg",
    "grafana",
    "hackerone",
    "hashicorp",
    "hiddenlayer",
    #"ibm",
    "icscert",
    "isc",
    "jenkins",
    "jetbrains",
    "jfrog",
    "jpcert",
    "kubernetes",
    "libreswan",
    #"microsoft",
    "mozilla",
    "nlnet labs",
    "nvidia",
    "openssl",
    "openvpn",
    "oracle",
    "ox",
    "patchstack",
    "php",
    "postgresql",
    "psf",
    #"redhat",
    "snyk",
    "tcpdump",
    "tenable",
    "tigera",
    "vulncheck",
    "wikimedia-foundation",
    "wolfssl",
    "wordfence",
    "wpscan",
    "zabbix",
]
deny = [
    "vuldb",
    "fluid attacks",
    "incibe",
    "google_devices",
    "sap",
    "liferay",
    "google_android",
]

[generate.cve]
deny = [
    "CVE-2024-2397",  # no released versions of tcpdump were affected, only a range of commits in master
    "CVE-2023-3966",
    "CVE-2024-1062",
    "CVE-2024-1722",  # no upstream version info provided by RedHat
    "CVE-2024-1485",  # no upstream version info provided by RedHat
    "CVE-2024-1342",  # no upstream version info provided by RedHat
    "CVE-2024-1454",  # no upstream version info provided by RedHat
    "CVE-2024-1151",  # Linux kernel
    "CVE-2023-6681",  # no upstream version info provided by RedHat
    "CVE-2024-2045",  # session android app
    "CVE-2023-6132",  # aviva edge
    "CVE-2024-20325",  # cisco
    "CVE-2024-20294",  # cisco possibly incorrect cve data
    "CVE-2024-1394",  # go-fips thing corresponding to https://github.com/advisories/GHSA-78hx-gp6g-7mj6 - several packages and no known CPEs
    # TODO: These are KeyCloak ones reported by RedHat, but we don't know what the upstream fix is yet
    # The maven GitHub data for all of the KeyCloak vulns seems less than ideal, but annoyingly RedHat don't seem to
    # link the upstream commits in their Bugzilla, so need to figure out how to find these.
    "CVE-2024-1132",
    "CVE-2024-2419",
    "CVE-2024-1249",
    "CVE-2023-3597",
    "CVE-2023-6484",
    "CVE-2023-6544",
    "CVE-2023-6717",
    "CVE-2023-6787",
    # TODO: same situation for quarkus
    "CVE-2023-5675",
    # TODO: additional redhat stuff to sort out
    "CVE-2023-6596",
    "CVE-2024-1657",
    "CVE-2023-5685",
    "CVE-2024-2494",
    "CVE-2024-29895", # The actual versions are not specified here.  It seems this was possibly only between unreleased commits but needs further investigation.
    "CVE-2024-4438",
    "CVE-2024-4438",
    "CVE-2023-6725",
    "CVE-2023-6725",
    "CVE-2024-4436",
    "CVE-2024-4437",

    # Tenable plugin feed vulns: Unsure how to represent these currently as the versions reported in the vulns do not represent product versions
    "CVE-2024-2390",
    "CVE-2024-29205", # Ivanti Connect Secure weird version ranges
    "CVE-2024-21424", # Azure Compute Gallery
    "CVE-2024-30042", # Microsoft Office stuff -> no real versions on many of the records
    "CVE-2024-40895", # jpcert vuln -> no idea what this is and not currently inclined to figure it out
    "CVE-2024-6098", # something we probably don't currently need to prioritise figuring out
    "CVE-2024-45798", # Appears to be something with GitHub actions in the repo, not the actual artifacts
    "CVE-2024-49521", # Appears to be some sort of Adobe SaaS service rather than the distributed artifacts
    "CVE-2024-7598", # Historical Kubernetes one, not going to try and track the "fixes" down at this time
    
    # probably nonsense
    "CVE-2025-24883",
    "CVE-2025-24885",
    "CVE-2025-24886",

    "CVE-2025-2867", # GitLab Duo with Amazon Q (this seems like it should be different than just normal GitLab since it is a non-common configuration, so we'll skip it for now and see if there is some sub-component later that could identify whether this is actually in use)
    "CVE-2022-21546", # Oracle VM Server, not going to attempt to track this down at this time
    
    # These have weird version ranges, ignore for now
    "CVE-2025-36539",
    "CVE-2025-44019", 

    "CVE-2024-4388", # auto lookup CPE is incorrect, there probably isn't a real one for it yet - Not going to waste time on this one currently
    
    # old chrome ones not worth bothering over
    "CVE-2010-1851",
    "CVE-2010-5069",
    "CVE-2010-5073",
]

[generate.cpe]
# filter out products we can't care about enriching missing data for right now
deny = [
    {vendor="freebsd", product="freebsd"},
    {vendor="microsoft", product="defender_for_endpoint"},
    {vendor="miraheze", product="managewiki"}, # only git repo commit info, no releases
    {vendor="cisco", product="unified_computing_system"},
    {vendor="cisco", product="ucs_central_software"},
    {vendor="cisco", product="ucs_manager"},
    {vendor="ibm", product="cics_tx"},
    {vendor="ibm", product="txseries_for_multiplatforms"},
    {vendor="ibm", product="txseries_for_multiplatform"},
    {vendor="oracle", product="solaris"},
    {vendor="netapp"},
]

[generate.vendor]
deny = [
    "netapp"
]